# Generated by Django 6.0.3 on 2026-03-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[("chat_message", "Chat Message"), ("tool_use", "Tool Use")],
                default="chat_message",
                max_length=20,
            ),
        ),
    ]
