# Generated by Django 6.0.3 on 2026-03-06 10:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_change_saved_memory_to_tool_use"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvalRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "eval_type",
                    models.CharField(
                        choices=[
                            ("harness", "Harness"),
                            ("agent_sdk", "Agent SDK"),
                            ("tests", "Tests"),
                        ],
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
